var webpack = require("webpack");
module.exports={
	entry:__dirname+"/src/main.js",
	output:{
		path:__dirname+"./public",
		filename:"bundle.js"
	},
	module:{
		loaders:[
			{
				test:/\.css$/,
				loader:"style-loader!css-loader"
			},
			{
				test:/\.js$/,
				exclude:/node_modules/,
				loader:"babel-loader",
				query:{
					presets:["es2015"]
				}
			}
		]
	},
	plugins:{
		new webpack.BannerPlugin("chenyufei")
	},
	devServer:{
		contentBase:"./public",
		historyApiFallback:true,
		inline:true
	}
}